name: Our Life in Photos
favicon: null
layout_spectrum: 0.08919005934149027
typography_spectrum: 0.9846996872220188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.36453882278874516
  lightness: 0.3764036970678717
  saturation: 0.8496098308824003
  rhythmicContrast: 0.01704516657628119
purpose: []
