name: Our Life in Photos
favicon: null
layout_spectrum: 0.37543
typography_spectrum: 0.30199
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3125
  lightness: 0.0625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
